// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PgAttribute struct {
	Attrelid     int32
	Attname      string
	Attnum       int32
	Atttypid     int32
	Attcollation int32
	Attisdropped bool
}

type PgCast struct {
	Castsource int32
	Casttarget int32
}

type PgCharacterSet struct {
	Encoding int32
	Name     string
}

type PgClass struct {
	Oid            int32
	Relname        string
	Relnamespace   int32
	Relkind        string
	Relowner       int32
	Reltablespace  int32
	Reltuples      float64
	Relhasindex    bool
	Relrowsecurity bool
	Relacl         []interface{}
}

type PgCollation struct {
	Oid      int32
	Collname string
}

type PgConstraint struct {
	Oid           int32
	Conname       string
	Contype       string
	Conrelid      int32
	Confrelid     int32
	Conkey        []int32
	Condeferrable bool
	Condeferred   bool
}

type PgDatabase struct {
	Oid           int32
	Datname       string
	Datallowconn  bool
	Datistemplate bool
}

type PgDepend struct {
	Classid     int32
	Objid       int32
	Refclassid  int32
	Refobjid    int32
	Refobjsubid int32
	Deptype     string
}

type PgEventTrigger struct {
	Evtname string
}

type PgExtension struct {
	Extname string
}

type PgForeignDataWrapper struct {
	Fdwname string
}

type PgIndex struct {
	Indexrelid   int32
	Indrelid     int32
	Indisunique  bool
	Indisprimary bool
}

type PgLanguage struct {
	Lanname string
	Lanispl bool
}

type PgMatview struct {
	Matviewname string
	Schemaname  string
}

type PgNamespace struct {
	Oid     int32
	Nspname string
}

type PgPolicy struct {
	Policyname string
	Schemaname string
	Tablename  string
}

type PgProc struct {
	Oid          int32
	Proname      string
	Pronamespace int32
	Prokind      string
}

type PgPublication struct {
	Pubname string
}

type PgRewrite struct {
	Oid     int32
	EvClass int32
}

type PgRole struct {
	Rolname string
}

type PgRule struct {
	Rulename   string
	Schemaname string
	Tablename  string
}

type PgSequence struct {
	Sequencename string
	Schemaname   string
}

type PgStatUserTable struct {
	Schemaname      string
	Relname         string
	SeqScan         int64
	SeqTupRead      int64
	IdxScan         int64
	IdxTupFetch     int64
	NTupIns         int64
	NTupUpd         int64
	NTupDel         int64
	NLiveTup        int64
	NDeadTup        int64
	LastVacuum      pgtype.Timestamptz
	LastAutovacuum  pgtype.Timestamptz
	LastAnalyze     pgtype.Timestamptz
	LastAutoanalyze pgtype.Timestamptz
}

type PgSubscription struct {
	Subname string
	Subdbid int32
}

type PgTable struct {
	Tablename  string
	Schemaname string
	Tableowner string
	Tablespace pgtype.Text
	Hasindexes bool
}

type PgTablespace struct {
	Oid     int32
	Spcname string
}

type PgTrigger struct {
	Tgname       string
	Tgrelid      int32
	Tgisinternal bool
}

type PgType struct {
	Typname      string
	Typtype      string
	Typnamespace int32
}

type PgView struct {
	Viewname   string
	Schemaname string
}
