// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDatabaseObjects = `-- name: CountDatabaseObjects :many
SELECT 'casts' AS category, count(*) AS n FROM pg_cast
UNION ALL SELECT 'catalogs', count(*) FROM pg_namespace ns1 WHERE ns1.nspname = 'information_schema' OR ns1.nspname LIKE 'pg\_%'
UNION ALL SELECT 'event-triggers', count(*) FROM pg_event_trigger
UNION ALL SELECT 'extensions', count(*) FROM pg_extension
UNION ALL SELECT 'foreign-data-wrappers', count(*) FROM pg_foreign_data_wrapper
UNION ALL SELECT 'languages', count(*) FROM pg_language l WHERE l.lanispl
UNION ALL SELECT 'publications', count(*) FROM pg_publication
UNION ALL SELECT 'schemas', count(*) FROM pg_namespace ns2 WHERE ns2.nspname NOT LIKE 'pg\_%' AND ns2.nspname <> 'information_schema'
UNION ALL SELECT 'subscriptions', count(*) FROM pg_subscription sub WHERE sub.subdbid = (SELECT oid FROM pg_database WHERE datname = current_database())
`

type CountDatabaseObjectsRow struct {
	Category string
	N        int64
}

func (q *Queries) CountDatabaseObjects(ctx context.Context) ([]CountDatabaseObjectsRow, error) {
	rows, err := q.db.Query(ctx, countDatabaseObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDatabaseObjectsRow
	for rows.Next() {
		var i CountDatabaseObjectsRow
		if err := rows.Scan(&i.Category, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSchemaObjects = `-- name: CountSchemaObjects :many
SELECT 'tables' AS category, count(*) AS n FROM pg_tables t WHERE t.schemaname = $1
UNION ALL SELECT 'views', count(*) FROM pg_views v WHERE v.schemaname = $1
UNION ALL SELECT 'materialized-views', count(*) FROM pg_matviews m WHERE m.schemaname = $1
UNION ALL SELECT 'sequences', count(*) FROM pg_sequences s WHERE s.schemaname = $1
UNION ALL SELECT 'functions', count(*) FROM pg_proc p
  JOIN pg_namespace n ON p.pronamespace = n.oid
  WHERE n.nspname = $1 AND p.prokind = 'f'
UNION ALL SELECT 'procedures', count(*) FROM pg_proc p2
  JOIN pg_namespace n2 ON p2.pronamespace = n2.oid
  WHERE n2.nspname = $1 AND p2.prokind = 'p'
UNION ALL SELECT 'types', count(*) FROM pg_type t1
  JOIN pg_namespace n3 ON t1.typnamespace = n3.oid
  WHERE n3.nspname = $1 AND t1.typtype IN ('c', 'e', 'r')
UNION ALL SELECT 'domains', count(*) FROM pg_type t2
  JOIN pg_namespace n4 ON t2.typnamespace = n4.oid
  WHERE n4.nspname = $1 AND t2.typtype = 'd'
`

type CountSchemaObjectsRow struct {
	Category string
	N        int64
}

func (q *Queries) CountSchemaObjects(ctx context.Context, schemaname string) ([]CountSchemaObjectsRow, error) {
	rows, err := q.db.Query(ctx, countSchemaObjects, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSchemaObjectsRow
	for rows.Next() {
		var i CountSchemaObjectsRow
		if err := rows.Scan(&i.Category, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countServerObjects = `-- name: CountServerObjects :many
SELECT 'databases' AS category, count(*) AS n FROM pg_database d WHERE d.datallowconn AND NOT d.datistemplate
UNION ALL SELECT 'roles', count(*) FROM pg_roles
UNION ALL SELECT 'tablespaces', count(*) FROM pg_tablespace
`

type CountServerObjectsRow struct {
	Category string
	N        int64
}

func (q *Queries) CountServerObjects(ctx context.Context) ([]CountServerObjectsRow, error) {
	rows, err := q.db.Query(ctx, countServerObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountServerObjectsRow
	for rows.Next() {
		var i CountServerObjectsRow
		if err := rows.Scan(&i.Category, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTableObjects = `-- name: CountTableObjects :many
SELECT 'columns' AS category, count(*) AS n FROM information_schema.columns col WHERE col.table_schema = $1 AND col.table_name = $2
UNION ALL SELECT 'constraints', count(*) FROM pg_constraint con
  JOIN pg_class cls ON con.conrelid = cls.oid
  JOIN pg_namespace ns ON cls.relnamespace = ns.oid
  WHERE ns.nspname = $1 AND cls.relname = $2
UNION ALL SELECT 'indexes', count(*) FROM pg_index idx
  JOIN pg_class cls ON cls.oid = idx.indexrelid
  JOIN pg_class tbl ON tbl.oid = idx.indrelid
  JOIN pg_namespace ns ON tbl.relnamespace = ns.oid
  WHERE ns.nspname = $1 AND tbl.relname = $2
UNION ALL SELECT 'rls-policies', count(*) FROM pg_policies pol WHERE pol.schemaname = $1 AND pol.tablename = $2
UNION ALL SELECT 'rules', count(*) FROM pg_rules rl WHERE rl.schemaname = $1 AND rl.tablename = $2
UNION ALL SELECT 'triggers', count(*) FROM pg_trigger trg
  JOIN pg_class cls2 ON trg.tgrelid = cls2.oid
  JOIN pg_namespace ns2 ON cls2.relnamespace = ns2.oid
  WHERE ns2.nspname = $1 AND cls2.relname = $2 AND NOT trg.tgisinternal
`

type CountTableObjectsParams struct {
	TableSchema interface{}
	TableName   interface{}
}

type CountTableObjectsRow struct {
	Category string
	N        int64
}

func (q *Queries) CountTableObjects(ctx context.Context, arg CountTableObjectsParams) ([]CountTableObjectsRow, error) {
	rows, err := q.db.Query(ctx, countTableObjects, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTableObjectsRow
	for rows.Next() {
		var i CountTableObjectsRow
		if err := rows.Scan(&i.Category, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCastGeneral = `-- name: GetCastGeneral :one
SELECT
    CASE c.castcontext WHEN 'e' THEN 'explicit' WHEN 'a' THEN 'assignment' ELSE 'implicit' END AS context,
    CASE c.castmethod WHEN 'f' THEN 'function' WHEN 'i' THEN 'inout' ELSE 'binary coercible' END AS method,
    c.castfunc::regproc::text AS function_name,
    COALESCE(obj_description(c.oid, 'pg_cast'), '') AS comment
FROM pg_cast c
WHERE c.castsource = $1::regtype AND c.casttarget = $2::regtype
LIMIT 1
`

type GetCastGeneralParams struct {
	Column1 interface{}
	Column2 interface{}
}

type GetCastGeneralRow struct {
	Context      string
	Method       string
	FunctionName string
	Comment      interface{}
}

func (q *Queries) GetCastGeneral(ctx context.Context, arg GetCastGeneralParams) (GetCastGeneralRow, error) {
	row := q.db.QueryRow(ctx, getCastGeneral, arg.Column1, arg.Column2)
	var i GetCastGeneralRow
	err := row.Scan(
		&i.Context,
		&i.Method,
		&i.FunctionName,
		&i.Comment,
	)
	return i, err
}

const getColumnDetail = `-- name: GetColumnDetail :one

SELECT
    c.column_name,
    c.data_type,
    c.is_nullable,
    c.column_default,
    c.character_maximum_length,
    COALESCE(coll.collname, '') AS collation,
    COALESCE(col_description(a.attrelid, a.attnum), '') AS comment
FROM information_schema.columns c
LEFT JOIN pg_attribute a ON a.attrelid = ($1 || '.' || $2)::regclass AND a.attname = c.column_name
LEFT JOIN pg_collation coll ON coll.oid = a.attcollation
WHERE c.table_schema = $1 AND c.table_name = $2 AND c.column_name = $3
LIMIT 1
`

type GetColumnDetailParams struct {
	Column1    pgtype.Text
	Column2    pgtype.Text
	ColumnName interface{}
}

type GetColumnDetailRow struct {
	ColumnName             interface{}
	DataType               interface{}
	IsNullable             interface{}
	ColumnDefault          interface{}
	CharacterMaximumLength interface{}
	Collation              string
	Comment                interface{}
}

// Plain-leaf object properties queries ("General + SQL" panel kinds without
// their own DDL yet: columns, constraints, RLS policies, rules, types,
// domains, casts, catalogs, event triggers, foreign data wrappers, languages,
// subscriptions).
func (q *Queries) GetColumnDetail(ctx context.Context, arg GetColumnDetailParams) (GetColumnDetailRow, error) {
	row := q.db.QueryRow(ctx, getColumnDetail, arg.Column1, arg.Column2, arg.ColumnName)
	var i GetColumnDetailRow
	err := row.Scan(
		&i.ColumnName,
		&i.DataType,
		&i.IsNullable,
		&i.ColumnDefault,
		&i.CharacterMaximumLength,
		&i.Collation,
		&i.Comment,
	)
	return i, err
}

const getConstraintDetail = `-- name: GetConstraintDetail :one
SELECT
    c.conname,
    c.contype::text AS constraint_type,
    pg_get_constraintdef(c.oid, true) AS definition,
    c.condeferrable,
    c.condeferred
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2 AND c.conname = $3
LIMIT 1
`

type GetConstraintDetailParams struct {
	Nspname string
	Relname string
	Conname string
}

type GetConstraintDetailRow struct {
	Conname        string
	ConstraintType string
	Definition     string
	Condeferrable  bool
	Condeferred    bool
}

func (q *Queries) GetConstraintDetail(ctx context.Context, arg GetConstraintDetailParams) (GetConstraintDetailRow, error) {
	row := q.db.QueryRow(ctx, getConstraintDetail, arg.Nspname, arg.Relname, arg.Conname)
	var i GetConstraintDetailRow
	err := row.Scan(
		&i.Conname,
		&i.ConstraintType,
		&i.Definition,
		&i.Condeferrable,
		&i.Condeferred,
	)
	return i, err
}

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT current_user
`

func (q *Queries) GetCurrentUser(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getCurrentUser)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getDomainGeneral = `-- name: GetDomainGeneral :one
SELECT
    t.oid::int4 AS type_oid,
    format_type(t.typbasetype, t.typtypmod) AS base_type,
    t.typnotnull AS not_null,
    COALESCE(t.typdefault, '') AS default_value,
    pg_get_userbyid(t.typowner) AS owner,
    COALESCE(obj_description(t.oid, 'pg_type'), '') AS comment
FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typname = $2 AND t.typtype = 'd'
LIMIT 1
`

type GetDomainGeneralParams struct {
	Nspname string
	Typname string
}

type GetDomainGeneralRow struct {
	TypeOid      int32
	BaseType     string
	NotNull      bool
	DefaultValue string
	Owner        string
	Comment      interface{}
}

func (q *Queries) GetDomainGeneral(ctx context.Context, arg GetDomainGeneralParams) (GetDomainGeneralRow, error) {
	row := q.db.QueryRow(ctx, getDomainGeneral, arg.Nspname, arg.Typname)
	var i GetDomainGeneralRow
	err := row.Scan(
		&i.TypeOid,
		&i.BaseType,
		&i.NotNull,
		&i.DefaultValue,
		&i.Owner,
		&i.Comment,
	)
	return i, err
}

const getEventTriggerGeneral = `-- name: GetEventTriggerGeneral :one
SELECT
    t.evtevent,
    CASE t.evtenabled
        WHEN 'O' THEN 'origin' WHEN 'D' THEN 'disabled'
        WHEN 'R' THEN 'replica' WHEN 'A' THEN 'always'
        ELSE t.evtenabled::text
    END AS enabled,
    pg_get_userbyid(t.evtowner) AS owner,
    t.evtfoid::regproc::text AS function_name,
    COALESCE(array_to_string(t.evttags, ', '), '') AS tags,
    COALESCE(obj_description(t.oid, 'pg_event_trigger'), '') AS comment
FROM pg_event_trigger t
WHERE t.evtname = $1
LIMIT 1
`

type GetEventTriggerGeneralRow struct {
	Evtevent     string
	Enabled      string
	Owner        string
	FunctionName string
	Tags         interface{}
	Comment      interface{}
}

func (q *Queries) GetEventTriggerGeneral(ctx context.Context, evtname string) (GetEventTriggerGeneralRow, error) {
	row := q.db.QueryRow(ctx, getEventTriggerGeneral, evtname)
	var i GetEventTriggerGeneralRow
	err := row.Scan(
		&i.Evtevent,
		&i.Enabled,
		&i.Owner,
		&i.FunctionName,
		&i.Tags,
		&i.Comment,
	)
	return i, err
}

const getForeignDataWrapperGeneral = `-- name: GetForeignDataWrapperGeneral :one
SELECT
    pg_get_userbyid(f.fdwowner) AS owner,
    f.fdwhandler::regproc::text AS handler,
    f.fdwvalidator::regproc::text AS validator,
    COALESCE(array_to_string(f.fdwoptions, ', '), '') AS options,
    COALESCE(obj_description(f.oid, 'pg_foreign_data_wrapper'), '') AS comment
FROM pg_foreign_data_wrapper f
WHERE f.fdwname = $1
LIMIT 1
`

type GetForeignDataWrapperGeneralRow struct {
	Owner     string
	Handler   string
	Validator string
	Options   interface{}
	Comment   interface{}
}

func (q *Queries) GetForeignDataWrapperGeneral(ctx context.Context, fdwname string) (GetForeignDataWrapperGeneralRow, error) {
	row := q.db.QueryRow(ctx, getForeignDataWrapperGeneral, fdwname)
	var i GetForeignDataWrapperGeneralRow
	err := row.Scan(
		&i.Owner,
		&i.Handler,
		&i.Validator,
		&i.Options,
		&i.Comment,
	)
	return i, err
}

const getFunctionDefinition = `-- name: GetFunctionDefinition :one
SELECT pg_get_functiondef(p.oid) AS definition
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = $1 AND (p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')') = $2
LIMIT 1
`

type GetFunctionDefinitionParams struct {
	Nspname string
	Proname string
}

func (q *Queries) GetFunctionDefinition(ctx context.Context, arg GetFunctionDefinitionParams) (string, error) {
	row := q.db.QueryRow(ctx, getFunctionDefinition, arg.Nspname, arg.Proname)
	var definition string
	err := row.Scan(&definition)
	return definition, err
}

const getFunctionGeneral = `-- name: GetFunctionGeneral :one
SELECT
    p.prokind::text AS kind,
    pg_get_function_identity_arguments(p.oid) AS identity_arguments,
    pg_get_function_arguments(p.oid) AS arguments,
    pg_get_function_result(p.oid) AS return_type,
    l.lanname AS language,
    CASE p.provolatile WHEN 'i' THEN 'immutable' WHEN 's' THEN 'stable' ELSE 'volatile' END AS volatility,
    p.prosecdef AS security_definer,
    p.proisstrict AS strict,
    CASE p.proparallel WHEN 's' THEN 'safe' WHEN 'r' THEN 'restricted' ELSE 'unsafe' END AS parallel,
    pg_get_userbyid(p.proowner) AS owner,
    COALESCE(obj_description(p.oid, 'pg_proc'), '') AS comment
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
JOIN pg_language l ON l.oid = p.prolang
WHERE n.nspname = $1 AND (p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')') = $2
LIMIT 1
`

type GetFunctionGeneralParams struct {
	Nspname string
	Proname string
}

type GetFunctionGeneralRow struct {
	Kind              string
	IdentityArguments string
	Arguments         string
	ReturnType        string
	Language          string
	Volatility        string
	SecurityDefiner   bool
	Strict            bool
	Parallel          string
	Owner             string
	Comment           interface{}
}

func (q *Queries) GetFunctionGeneral(ctx context.Context, arg GetFunctionGeneralParams) (GetFunctionGeneralRow, error) {
	row := q.db.QueryRow(ctx, getFunctionGeneral, arg.Nspname, arg.Proname)
	var i GetFunctionGeneralRow
	err := row.Scan(
		&i.Kind,
		&i.IdentityArguments,
		&i.Arguments,
		&i.ReturnType,
		&i.Language,
		&i.Volatility,
		&i.SecurityDefiner,
		&i.Strict,
		&i.Parallel,
		&i.Owner,
		&i.Comment,
	)
	return i, err
}

const getIndexColumns = `-- name: GetIndexColumns :many
SELECT
    COALESCE(pg_get_indexdef(i.indexrelid, g.ord::int, true), '') AS column_def
FROM pg_index i
JOIN pg_class c ON c.oid = i.indexrelid
JOIN pg_class tc ON tc.oid = i.indrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
JOIN generate_series(1, i.indnkeyatts) AS g(ord) ON true
WHERE n.nspname = $1 AND tc.relname = $2 AND c.relname = $3
ORDER BY g.ord
`

type GetIndexColumnsParams struct {
	Nspname   string
	Relname   string
	Relname_2 string
}

func (q *Queries) GetIndexColumns(ctx context.Context, arg GetIndexColumnsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getIndexColumns, arg.Nspname, arg.Relname, arg.Relname_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_def interface{}
		if err := rows.Scan(&column_def); err != nil {
			return nil, err
		}
		items = append(items, column_def)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexGeneral = `-- name: GetIndexGeneral :one
SELECT
    c.relname AS index_name,
    pg_get_indexdef(i.indexrelid, 0, true) AS definition,
    i.indisunique AS is_unique,
    COALESCE(t.spcname, 'pg_default') AS tablespace,
    am.amname AS access_method,
    pg_get_userbyid(c.relowner) AS owner,
    pg_relation_size(i.indexrelid) AS relation_size,
    COALESCE(obj_description(i.indexrelid), '') AS comment
FROM pg_index i
JOIN pg_class c ON c.oid = i.indexrelid
JOIN pg_class tc ON tc.oid = i.indrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
LEFT JOIN pg_tablespace t ON t.oid = c.reltablespace
JOIN pg_am am ON am.oid = c.relam
WHERE n.nspname = $1 AND tc.relname = $2 AND c.relname = $3
LIMIT 1
`

type GetIndexGeneralParams struct {
	Nspname   string
	Relname   string
	Relname_2 string
}

type GetIndexGeneralRow struct {
	IndexName    string
	Definition   string
	IsUnique     bool
	Tablespace   string
	AccessMethod string
	Owner        string
	RelationSize int64
	Comment      interface{}
}

func (q *Queries) GetIndexGeneral(ctx context.Context, arg GetIndexGeneralParams) (GetIndexGeneralRow, error) {
	row := q.db.QueryRow(ctx, getIndexGeneral, arg.Nspname, arg.Relname, arg.Relname_2)
	var i GetIndexGeneralRow
	err := row.Scan(
		&i.IndexName,
		&i.Definition,
		&i.IsUnique,
		&i.Tablespace,
		&i.AccessMethod,
		&i.Owner,
		&i.RelationSize,
		&i.Comment,
	)
	return i, err
}

const getLanguageGeneral = `-- name: GetLanguageGeneral :one
SELECT
    l.lanpltrusted AS trusted,
    pg_get_userbyid(l.lanowner) AS owner,
    l.lanplcallfoid::regproc::text AS call_handler,
    l.laninline::regproc::text AS inline_handler,
    l.lanvalidator::regproc::text AS validator,
    COALESCE(obj_description(l.oid, 'pg_language'), '') AS comment
FROM pg_language l
WHERE l.lanname = $1
LIMIT 1
`

type GetLanguageGeneralRow struct {
	Trusted       bool
	Owner         string
	CallHandler   string
	InlineHandler string
	Validator     string
	Comment       interface{}
}

func (q *Queries) GetLanguageGeneral(ctx context.Context, lanname string) (GetLanguageGeneralRow, error) {
	row := q.db.QueryRow(ctx, getLanguageGeneral, lanname)
	var i GetLanguageGeneralRow
	err := row.Scan(
		&i.Trusted,
		&i.Owner,
		&i.CallHandler,
		&i.InlineHandler,
		&i.Validator,
		&i.Comment,
	)
	return i, err
}

const getMatViewColumnsDetailed = `-- name: GetMatViewColumnsDetailed :many
SELECT
    a.attname AS column_name,
    format_type(a.atttypid, a.atttypmod) AS data_type,
    CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END AS is_nullable,
    COALESCE(pg_get_expr(d.adbin, d.adrelid), '') AS column_default,
    CASE
        WHEN a.atttypid IN ('varchar'::regtype, 'bpchar'::regtype) THEN NULLIF(a.atttypmod, -1) - 4
        ELSE NULL
    END AS character_maximum_length,
    COALESCE(colsh.collname, '') AS collation,
    COALESCE(col_description(a.attrelid, a.attnum), '') AS comment
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
LEFT JOIN pg_collation colsh ON colsh.oid = a.attcollation
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'm'
  AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
`

type GetMatViewColumnsDetailedParams struct {
	Nspname string
	Relname string
}

type GetMatViewColumnsDetailedRow struct {
	ColumnName             string
	DataType               string
	IsNullable             string
	ColumnDefault          interface{}
	CharacterMaximumLength interface{}
	Collation              string
	Comment                interface{}
}

func (q *Queries) GetMatViewColumnsDetailed(ctx context.Context, arg GetMatViewColumnsDetailedParams) ([]GetMatViewColumnsDetailedRow, error) {
	rows, err := q.db.Query(ctx, getMatViewColumnsDetailed, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatViewColumnsDetailedRow
	for rows.Next() {
		var i GetMatViewColumnsDetailedRow
		if err := rows.Scan(
			&i.ColumnName,
			&i.DataType,
			&i.IsNullable,
			&i.ColumnDefault,
			&i.CharacterMaximumLength,
			&i.Collation,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatViewDefinition = `-- name: GetMatViewDefinition :one
SELECT pg_get_viewdef(c.oid, true)::text AS definition
FROM pg_class c
JOIN pg_namespace n ON c.relnamespace = n.oid
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'm'
LIMIT 1
`

type GetMatViewDefinitionParams struct {
	Nspname string
	Relname string
}

func (q *Queries) GetMatViewDefinition(ctx context.Context, arg GetMatViewDefinitionParams) (string, error) {
	row := q.db.QueryRow(ctx, getMatViewDefinition, arg.Nspname, arg.Relname)
	var definition string
	err := row.Scan(&definition)
	return definition, err
}

const getMatViewGeneral = `-- name: GetMatViewGeneral :one
SELECT
    pg_get_userbyid(c.relowner) AS owner,
    pg_total_relation_size(c.oid) AS relation_size,
    c.reltuples::bigint AS row_estimate,
    c.relhasindex AS has_indexes,
    COALESCE(obj_description(c.oid), '') AS comment,
    (SELECT count(*) FROM pg_attribute a
     WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped) AS column_count
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'm'
LIMIT 1
`

type GetMatViewGeneralParams struct {
	Nspname string
	Relname string
}

type GetMatViewGeneralRow struct {
	Owner        string
	RelationSize int64
	RowEstimate  int64
	HasIndexes   bool
	Comment      interface{}
	ColumnCount  int64
}

func (q *Queries) GetMatViewGeneral(ctx context.Context, arg GetMatViewGeneralParams) (GetMatViewGeneralRow, error) {
	row := q.db.QueryRow(ctx, getMatViewGeneral, arg.Nspname, arg.Relname)
	var i GetMatViewGeneralRow
	err := row.Scan(
		&i.Owner,
		&i.RelationSize,
		&i.RowEstimate,
		&i.HasIndexes,
		&i.Comment,
		&i.ColumnCount,
	)
	return i, err
}

const getObjectDependencies = `-- name: GetObjectDependencies :many
SELECT 'view' AS kind,
    dep_ns.nspname || '.' || dep_rel.relname AS name,
    '' AS detail
FROM pg_depend d
JOIN pg_rewrite r ON r.oid = d.objid
JOIN pg_class dep_rel ON dep_rel.oid = r.ev_class
JOIN pg_namespace dep_ns ON dep_ns.oid = dep_rel.relnamespace
JOIN pg_class src ON src.oid = d.refobjid
JOIN pg_namespace src_ns ON src_ns.oid = src.relnamespace
WHERE src_ns.nspname = $1 AND src.relname = $2 AND dep_rel.relkind = 'v'
UNION ALL
SELECT 'foreign key',
    ref_ns.nspname || '.' || ref_rel.relname,
    con.conname
FROM pg_constraint con
JOIN pg_class key_rel ON key_rel.oid = con.confrelid
JOIN pg_namespace key_ns ON key_ns.oid = key_rel.relnamespace
JOIN pg_class ref_rel ON ref_rel.oid = con.conrelid
JOIN pg_namespace ref_ns ON ref_ns.oid = ref_rel.relnamespace
WHERE key_ns.nspname = $1 AND key_rel.relname = $2 AND con.contype = 'f'
UNION ALL
SELECT 'index',
    n.nspname || '.' || c.relname,
    ''
FROM pg_index i
JOIN pg_class c ON c.oid = i.indexrelid
JOIN pg_class tc ON tc.oid = i.indrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
WHERE n.nspname = $1 AND tc.relname = $2
ORDER BY 1, 2
`

type GetObjectDependenciesParams struct {
	Nspname string
	Relname string
}

type GetObjectDependenciesRow struct {
	Kind   string
	Name   interface{}
	Detail string
}

func (q *Queries) GetObjectDependencies(ctx context.Context, arg GetObjectDependenciesParams) ([]GetObjectDependenciesRow, error) {
	rows, err := q.db.Query(ctx, getObjectDependencies, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObjectDependenciesRow
	for rows.Next() {
		var i GetObjectDependenciesRow
		if err := rows.Scan(&i.Kind, &i.Name, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectPrivileges = `-- name: GetObjectPrivileges :many
SELECT
    grantee,
    privilege_type,
    is_grantable
FROM information_schema.table_privileges
WHERE table_schema = $1 AND table_name = $2
ORDER BY grantee, privilege_type
`

type GetObjectPrivilegesParams struct {
	TableSchema interface{}
	TableName   interface{}
}

type GetObjectPrivilegesRow struct {
	Grantee       interface{}
	PrivilegeType interface{}
	IsGrantable   interface{}
}

func (q *Queries) GetObjectPrivileges(ctx context.Context, arg GetObjectPrivilegesParams) ([]GetObjectPrivilegesRow, error) {
	rows, err := q.db.Query(ctx, getObjectPrivileges, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObjectPrivilegesRow
	for rows.Next() {
		var i GetObjectPrivilegesRow
		if err := rows.Scan(&i.Grantee, &i.PrivilegeType, &i.IsGrantable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyGeneral = `-- name: GetPolicyGeneral :one
SELECT
    p.permissive,
    array_to_string(p.roles, ', ') AS roles,
    p.cmd,
    COALESCE(p.qual, '') AS using_expr,
    COALESCE(p.with_check, '') AS with_check_expr
FROM pg_policies p
WHERE p.schemaname = $1 AND p.tablename = $2 AND p.policyname = $3
LIMIT 1
`

type GetPolicyGeneralParams struct {
	Schemaname string
	Tablename  string
	Policyname string
}

type GetPolicyGeneralRow struct {
	Permissive    string
	Roles         string
	Cmd           string
	UsingExpr     string
	WithCheckExpr string
}

func (q *Queries) GetPolicyGeneral(ctx context.Context, arg GetPolicyGeneralParams) (GetPolicyGeneralRow, error) {
	row := q.db.QueryRow(ctx, getPolicyGeneral, arg.Schemaname, arg.Tablename, arg.Policyname)
	var i GetPolicyGeneralRow
	err := row.Scan(
		&i.Permissive,
		&i.Roles,
		&i.Cmd,
		&i.UsingExpr,
		&i.WithCheckExpr,
	)
	return i, err
}

const getPrimaryKeyColumns = `-- name: GetPrimaryKeyColumns :many
SELECT c.conname, a.attname
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
JOIN unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
WHERE n.nspname = $1 AND t.relname = $2 AND c.contype = 'p'
ORDER BY k.ord
`

type GetPrimaryKeyColumnsParams struct {
	Nspname string
	Relname string
}

type GetPrimaryKeyColumnsRow struct {
	Conname string
	Attname string
}

func (q *Queries) GetPrimaryKeyColumns(ctx context.Context, arg GetPrimaryKeyColumnsParams) ([]GetPrimaryKeyColumnsRow, error) {
	rows, err := q.db.Query(ctx, getPrimaryKeyColumns, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrimaryKeyColumnsRow
	for rows.Next() {
		var i GetPrimaryKeyColumnsRow
		if err := rows.Scan(&i.Conname, &i.Attname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRangeSubtype = `-- name: GetRangeSubtype :one
SELECT format_type(r.rngsubtype, NULL) AS subtype
FROM pg_range r
WHERE r.rngtypid::int4 = $1
LIMIT 1
`

func (q *Queries) GetRangeSubtype(ctx context.Context, rngtypid int32) (string, error) {
	row := q.db.QueryRow(ctx, getRangeSubtype, rngtypid)
	var subtype string
	err := row.Scan(&subtype)
	return subtype, err
}

const getRuleDefinition = `-- name: GetRuleDefinition :one
SELECT r.definition
FROM pg_rules r
WHERE r.schemaname = $1 AND r.tablename = $2 AND r.rulename = $3
LIMIT 1
`

type GetRuleDefinitionParams struct {
	Schemaname string
	Tablename  string
	Rulename   string
}

func (q *Queries) GetRuleDefinition(ctx context.Context, arg GetRuleDefinitionParams) (string, error) {
	row := q.db.QueryRow(ctx, getRuleDefinition, arg.Schemaname, arg.Tablename, arg.Rulename)
	var definition string
	err := row.Scan(&definition)
	return definition, err
}

const getSchemaGeneral = `-- name: GetSchemaGeneral :one
SELECT
    pg_get_userbyid(n.nspowner) AS owner,
    COALESCE(obj_description(n.oid), '') AS comment
FROM pg_namespace n
WHERE n.nspname = $1
LIMIT 1
`

type GetSchemaGeneralRow struct {
	Owner   string
	Comment interface{}
}

func (q *Queries) GetSchemaGeneral(ctx context.Context, nspname string) (GetSchemaGeneralRow, error) {
	row := q.db.QueryRow(ctx, getSchemaGeneral, nspname)
	var i GetSchemaGeneralRow
	err := row.Scan(&i.Owner, &i.Comment)
	return i, err
}

const getSequenceGeneral = `-- name: GetSequenceGeneral :one
SELECT
    s.data_type,
    s.start_value,
    s.min_value,
    s.max_value,
    s.increment_by,
    s.cycle,
    s.cache_size,
    s.last_value,
    pg_get_userbyid(c.relowner) AS owner,
    pg_relation_size(c.oid) AS relation_size,
    COALESCE(obj_description(c.oid), '') AS comment
FROM pg_sequences s
JOIN pg_class c ON c.relname = s.sequencename AND c.relkind = 'S'
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = s.schemaname
WHERE s.schemaname = $1 AND s.sequencename = $2
LIMIT 1
`

type GetSequenceGeneralParams struct {
	Schemaname   string
	Sequencename string
}

type GetSequenceGeneralRow struct {
	DataType     pgtype.Text
	StartValue   pgtype.Int8
	MinValue     pgtype.Int8
	MaxValue     pgtype.Int8
	IncrementBy  pgtype.Int8
	Cycle        pgtype.Bool
	CacheSize    pgtype.Int8
	LastValue    pgtype.Int8
	Owner        string
	RelationSize int64
	Comment      interface{}
}

func (q *Queries) GetSequenceGeneral(ctx context.Context, arg GetSequenceGeneralParams) (GetSequenceGeneralRow, error) {
	row := q.db.QueryRow(ctx, getSequenceGeneral, arg.Schemaname, arg.Sequencename)
	var i GetSequenceGeneralRow
	err := row.Scan(
		&i.DataType,
		&i.StartValue,
		&i.MinValue,
		&i.MaxValue,
		&i.IncrementBy,
		&i.Cycle,
		&i.CacheSize,
		&i.LastValue,
		&i.Owner,
		&i.RelationSize,
		&i.Comment,
	)
	return i, err
}

const getSubscriptionGeneral = `-- name: GetSubscriptionGeneral :one
SELECT
    pg_get_userbyid(s.subowner) AS owner,
    s.subenabled AS enabled,
    array_to_string(s.subpublications, ', ') AS publications,
    COALESCE(s.subslotname, '') AS slot_name,
    COALESCE(obj_description(s.oid, 'pg_subscription'), '') AS comment
FROM pg_subscription s
WHERE s.subdbid = (SELECT oid FROM pg_database WHERE datname = current_database())
  AND s.subname = $1
LIMIT 1
`

type GetSubscriptionGeneralRow struct {
	Owner        string
	Enabled      bool
	Publications string
	SlotName     string
	Comment      interface{}
}

func (q *Queries) GetSubscriptionGeneral(ctx context.Context, subname string) (GetSubscriptionGeneralRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionGeneral, subname)
	var i GetSubscriptionGeneralRow
	err := row.Scan(
		&i.Owner,
		&i.Enabled,
		&i.Publications,
		&i.SlotName,
		&i.Comment,
	)
	return i, err
}

const getTableColumns = `-- name: GetTableColumns :many

SELECT column_name FROM information_schema.columns
WHERE table_schema = $1 AND table_name = $2
ORDER BY ordinal_position
`

type GetTableColumnsParams struct {
	TableSchema interface{}
	TableName   interface{}
}

// Table-level category queries ($1 = schema name, $2 = table name)
func (q *Queries) GetTableColumns(ctx context.Context, arg GetTableColumnsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getTableColumns, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_name interface{}
		if err := rows.Scan(&column_name); err != nil {
			return nil, err
		}
		items = append(items, column_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableColumnsDetailed = `-- name: GetTableColumnsDetailed :many
SELECT
    c.column_name,
    c.data_type,
    c.is_nullable,
    c.column_default,
    c.character_maximum_length,
    COALESCE(coll.collname, '') AS collation,
    COALESCE(col_description(a.attrelid, a.attnum), '') AS comment
FROM information_schema.columns c
LEFT JOIN pg_attribute a ON a.attrelid = ($1 || '.' || $2)::regclass AND a.attname = c.column_name
LEFT JOIN pg_collation coll ON coll.oid = a.attcollation
WHERE c.table_schema = $1 AND c.table_name = $2
ORDER BY c.ordinal_position
`

type GetTableColumnsDetailedParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
}

type GetTableColumnsDetailedRow struct {
	ColumnName             interface{}
	DataType               interface{}
	IsNullable             interface{}
	ColumnDefault          interface{}
	CharacterMaximumLength interface{}
	Collation              string
	Comment                interface{}
}

func (q *Queries) GetTableColumnsDetailed(ctx context.Context, arg GetTableColumnsDetailedParams) ([]GetTableColumnsDetailedRow, error) {
	rows, err := q.db.Query(ctx, getTableColumnsDetailed, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableColumnsDetailedRow
	for rows.Next() {
		var i GetTableColumnsDetailedRow
		if err := rows.Scan(
			&i.ColumnName,
			&i.DataType,
			&i.IsNullable,
			&i.ColumnDefault,
			&i.CharacterMaximumLength,
			&i.Collation,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableConstraints = `-- name: GetTableConstraints :many
SELECT
    c.conname,
    c.contype::text AS constraint_type,
    pg_get_constraintdef(c.oid, true) AS definition,
    c.condeferrable,
    c.condeferred
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2
ORDER BY c.conname
`

type GetTableConstraintsParams struct {
	Nspname string
	Relname string
}

type GetTableConstraintsRow struct {
	Conname        string
	ConstraintType string
	Definition     string
	Condeferrable  bool
	Condeferred    bool
}

func (q *Queries) GetTableConstraints(ctx context.Context, arg GetTableConstraintsParams) ([]GetTableConstraintsRow, error) {
	rows, err := q.db.Query(ctx, getTableConstraints, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableConstraintsRow
	for rows.Next() {
		var i GetTableConstraintsRow
		if err := rows.Scan(
			&i.Conname,
			&i.ConstraintType,
			&i.Definition,
			&i.Condeferrable,
			&i.Condeferred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableGeneral = `-- name: GetTableGeneral :one

SELECT
    t.tableowner,
    COALESCE(t.tablespace, 'pg_default') AS tablespace,
    COALESCE(obj_description(c.oid), '') AS comment,
    c.reltuples::bigint AS row_estimate,
    pg_total_relation_size(c.oid) AS table_size,
    t.hasindexes AS has_indexes,
    c.relkind::text = 'p' AS partitioned,
    c.relrowsecurity AS row_security
FROM pg_tables t
JOIN pg_class c ON c.relname = t.tablename
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = t.schemaname
WHERE t.schemaname = $1 AND t.tablename = $2
LIMIT 1
`

type GetTableGeneralParams struct {
	Schemaname string
	Tablename  string
}

type GetTableGeneralRow struct {
	Tableowner  string
	Tablespace  string
	Comment     interface{}
	RowEstimate int64
	TableSize   int64
	HasIndexes  bool
	Partitioned bool
	RowSecurity bool
}

// Object-properties queries (run against a specific database)
func (q *Queries) GetTableGeneral(ctx context.Context, arg GetTableGeneralParams) (GetTableGeneralRow, error) {
	row := q.db.QueryRow(ctx, getTableGeneral, arg.Schemaname, arg.Tablename)
	var i GetTableGeneralRow
	err := row.Scan(
		&i.Tableowner,
		&i.Tablespace,
		&i.Comment,
		&i.RowEstimate,
		&i.TableSize,
		&i.HasIndexes,
		&i.Partitioned,
		&i.RowSecurity,
	)
	return i, err
}

const getTableIndexesDetailed = `-- name: GetTableIndexesDetailed :many
SELECT
    c.relname AS index_name,
    pg_get_indexdef(i.indexrelid, 0, true) AS definition,
    i.indisunique AS is_unique,
    COALESCE(t.spcname, 'pg_default') AS tablespace,
    COALESCE(obj_description(i.indexrelid), '') AS comment
FROM pg_index i
JOIN pg_class c ON c.oid = i.indexrelid
JOIN pg_class tc ON tc.oid = i.indrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
LEFT JOIN pg_tablespace t ON t.oid = c.reltablespace
WHERE n.nspname = $1 AND tc.relname = $2
ORDER BY c.relname
`

type GetTableIndexesDetailedParams struct {
	Nspname string
	Relname string
}

type GetTableIndexesDetailedRow struct {
	IndexName  string
	Definition string
	IsUnique   bool
	Tablespace string
	Comment    interface{}
}

func (q *Queries) GetTableIndexesDetailed(ctx context.Context, arg GetTableIndexesDetailedParams) ([]GetTableIndexesDetailedRow, error) {
	rows, err := q.db.Query(ctx, getTableIndexesDetailed, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableIndexesDetailedRow
	for rows.Next() {
		var i GetTableIndexesDetailedRow
		if err := rows.Scan(
			&i.IndexName,
			&i.Definition,
			&i.IsUnique,
			&i.Tablespace,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableInfo = `-- name: GetTableInfo :one
SELECT tableowner, tablespace
FROM pg_tables
WHERE schemaname = $1 AND tablename = $2
LIMIT 1
`

type GetTableInfoParams struct {
	Schemaname string
	Tablename  string
}

type GetTableInfoRow struct {
	Tableowner string
	Tablespace pgtype.Text
}

func (q *Queries) GetTableInfo(ctx context.Context, arg GetTableInfoParams) (GetTableInfoRow, error) {
	row := q.db.QueryRow(ctx, getTableInfo, arg.Schemaname, arg.Tablename)
	var i GetTableInfoRow
	err := row.Scan(&i.Tableowner, &i.Tablespace)
	return i, err
}

const getTableStatistics = `-- name: GetTableStatistics :one
SELECT
    s.seq_scan, s.seq_tup_read, s.idx_scan, s.idx_tup_fetch,
    s.n_tup_ins, s.n_tup_upd, s.n_tup_del,
    s.n_live_tup, s.n_dead_tup,
    s.last_vacuum, s.last_autovacuum, s.last_analyze, s.last_autoanalyze
FROM pg_stat_user_tables s
WHERE s.schemaname = $1 AND s.relname = $2
LIMIT 1
`

type GetTableStatisticsParams struct {
	Schemaname string
	Relname    string
}

type GetTableStatisticsRow struct {
	SeqScan         int64
	SeqTupRead      int64
	IdxScan         int64
	IdxTupFetch     int64
	NTupIns         int64
	NTupUpd         int64
	NTupDel         int64
	NLiveTup        int64
	NDeadTup        int64
	LastVacuum      pgtype.Timestamptz
	LastAutovacuum  pgtype.Timestamptz
	LastAnalyze     pgtype.Timestamptz
	LastAutoanalyze pgtype.Timestamptz
}

func (q *Queries) GetTableStatistics(ctx context.Context, arg GetTableStatisticsParams) (GetTableStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getTableStatistics, arg.Schemaname, arg.Relname)
	var i GetTableStatisticsRow
	err := row.Scan(
		&i.SeqScan,
		&i.SeqTupRead,
		&i.IdxScan,
		&i.IdxTupFetch,
		&i.NTupIns,
		&i.NTupUpd,
		&i.NTupDel,
		&i.NLiveTup,
		&i.NDeadTup,
		&i.LastVacuum,
		&i.LastAutovacuum,
		&i.LastAnalyze,
		&i.LastAutoanalyze,
	)
	return i, err
}

const getTriggerGeneral = `-- name: GetTriggerGeneral :one
SELECT
    t.tgname,
    CASE
        WHEN t.tgtype & 2 = 2 THEN 'BEFORE'
        WHEN t.tgtype & 64 = 64 THEN 'INSTEAD OF'
        ELSE 'AFTER'
    END AS timing,
    rtrim(
        CASE WHEN t.tgtype & 4 = 4 THEN 'INSERT ' ELSE '' END ||
        CASE WHEN t.tgtype & 8 = 8 THEN 'DELETE ' ELSE '' END ||
        CASE WHEN t.tgtype & 16 = 16 THEN 'UPDATE ' ELSE '' END ||
        CASE WHEN t.tgtype & 32 = 32 THEN 'TRUNCATE ' ELSE '' END
    ) AS events,
    CASE t.tgenabled
        WHEN 'O' THEN 'origin'
        WHEN 'D' THEN 'disabled'
        WHEN 'R' THEN 'replica'
        WHEN 'A' THEN 'always'
        ELSE t.tgenabled::text
    END AS enabled,
    t.tgfoid::regproc::text AS function_name,
    quote_ident(n.nspname) || '.' || quote_ident(tc.relname) AS table_name,
    pg_get_triggerdef(t.oid) AS definition,
    COALESCE(obj_description(t.oid, 'pg_trigger'), '') AS comment
FROM pg_trigger t
JOIN pg_class tc ON tc.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
WHERE n.nspname = $1 AND tc.relname = $2 AND t.tgname = $3 AND NOT t.tgisinternal
LIMIT 1
`

type GetTriggerGeneralParams struct {
	Nspname string
	Relname string
	Tgname  string
}

type GetTriggerGeneralRow struct {
	Tgname       string
	Timing       string
	Events       string
	Enabled      string
	FunctionName string
	TableName    interface{}
	Definition   string
	Comment      interface{}
}

func (q *Queries) GetTriggerGeneral(ctx context.Context, arg GetTriggerGeneralParams) (GetTriggerGeneralRow, error) {
	row := q.db.QueryRow(ctx, getTriggerGeneral, arg.Nspname, arg.Relname, arg.Tgname)
	var i GetTriggerGeneralRow
	err := row.Scan(
		&i.Tgname,
		&i.Timing,
		&i.Events,
		&i.Enabled,
		&i.FunctionName,
		&i.TableName,
		&i.Definition,
		&i.Comment,
	)
	return i, err
}

const getTypeGeneral = `-- name: GetTypeGeneral :one
SELECT
    t.oid::int4 AS type_oid,
    t.typtype::text AS type_category,
    pg_get_userbyid(t.typowner) AS owner,
    COALESCE(obj_description(t.oid, 'pg_type'), '') AS comment
FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typname = $2 AND t.typtype IN ('c', 'e', 'r')
LIMIT 1
`

type GetTypeGeneralParams struct {
	Nspname string
	Typname string
}

type GetTypeGeneralRow struct {
	TypeOid      int32
	TypeCategory string
	Owner        string
	Comment      interface{}
}

func (q *Queries) GetTypeGeneral(ctx context.Context, arg GetTypeGeneralParams) (GetTypeGeneralRow, error) {
	row := q.db.QueryRow(ctx, getTypeGeneral, arg.Nspname, arg.Typname)
	var i GetTypeGeneralRow
	err := row.Scan(
		&i.TypeOid,
		&i.TypeCategory,
		&i.Owner,
		&i.Comment,
	)
	return i, err
}

const getViewDefinition = `-- name: GetViewDefinition :one
SELECT pg_get_viewdef(c.oid, true)::text AS definition
FROM pg_class c
JOIN pg_namespace n ON c.relnamespace = n.oid
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'v'
LIMIT 1
`

type GetViewDefinitionParams struct {
	Nspname string
	Relname string
}

func (q *Queries) GetViewDefinition(ctx context.Context, arg GetViewDefinitionParams) (string, error) {
	row := q.db.QueryRow(ctx, getViewDefinition, arg.Nspname, arg.Relname)
	var definition string
	err := row.Scan(&definition)
	return definition, err
}

const getViewGeneral = `-- name: GetViewGeneral :one
SELECT
    pg_get_userbyid(c.relowner) AS owner,
    pg_relation_size(c.oid) AS relation_size,
    COALESCE(obj_description(c.oid), '') AS comment,
    (SELECT count(*) FROM pg_attribute a
     WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped) AS column_count
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'v'
LIMIT 1
`

type GetViewGeneralParams struct {
	Nspname string
	Relname string
}

type GetViewGeneralRow struct {
	Owner        string
	RelationSize int64
	Comment      interface{}
	ColumnCount  int64
}

func (q *Queries) GetViewGeneral(ctx context.Context, arg GetViewGeneralParams) (GetViewGeneralRow, error) {
	row := q.db.QueryRow(ctx, getViewGeneral, arg.Nspname, arg.Relname)
	var i GetViewGeneralRow
	err := row.Scan(
		&i.Owner,
		&i.RelationSize,
		&i.Comment,
		&i.ColumnCount,
	)
	return i, err
}

const listAvailableExtensions = `-- name: ListAvailableExtensions :many
SELECT name FROM pg_available_extensions
WHERE name NOT IN (SELECT extname FROM pg_extension)
ORDER BY 1
`

func (q *Queries) ListAvailableExtensions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAvailableExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasts = `-- name: ListCasts :many

SELECT '(' || castsource::regtype || ' AS ' || casttarget::regtype || ')' FROM pg_cast ORDER BY 1
`

// Database-level category queries (run against a specific database)
func (q *Queries) ListCasts(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listCasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCastsDetailed = `-- name: ListCastsDetailed :many
SELECT castsource::regtype::text AS source_type, casttarget::regtype::text AS target_type
FROM pg_cast
ORDER BY 1, 2
`

type ListCastsDetailedRow struct {
	SourceType string
	TargetType string
}

func (q *Queries) ListCastsDetailed(ctx context.Context) ([]ListCastsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCastsDetailed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCastsDetailedRow
	for rows.Next() {
		var i ListCastsDetailedRow
		if err := rows.Scan(&i.SourceType, &i.TargetType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogs = `-- name: ListCatalogs :many
SELECT nspname FROM pg_namespace
WHERE nspname = 'information_schema' OR nspname LIKE 'pg\_%'
ORDER BY 1
`

func (q *Queries) ListCatalogs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCatalogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nspname string
		if err := rows.Scan(&nspname); err != nil {
			return nil, err
		}
		items = append(items, nspname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompositeAttributes = `-- name: ListCompositeAttributes :many
SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type
FROM pg_attribute a
WHERE a.attrelid = (SELECT typrelid FROM pg_type WHERE oid::int4 = $1)
  AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
`

type ListCompositeAttributesRow struct {
	Attname  string
	DataType string
}

func (q *Queries) ListCompositeAttributes(ctx context.Context, oid int32) ([]ListCompositeAttributesRow, error) {
	rows, err := q.db.Query(ctx, listCompositeAttributes, oid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompositeAttributesRow
	for rows.Next() {
		var i ListCompositeAttributesRow
		if err := rows.Scan(&i.Attname, &i.DataType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstraints = `-- name: ListConstraints :many
SELECT c.conname || ' (' || CASE c.contype
    WHEN 'p' THEN 'primary key'
    WHEN 'f' THEN 'foreign key'
    WHEN 'u' THEN 'unique'
    WHEN 'c' THEN 'check'
    ELSE c.contype::text
END || ')'
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2
ORDER BY 1
`

type ListConstraintsParams struct {
	Nspname string
	Relname string
}

func (q *Queries) ListConstraints(ctx context.Context, arg ListConstraintsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listConstraints, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseTemplates = `-- name: ListDatabaseTemplates :many
SELECT datname FROM pg_database
WHERE datistemplate
ORDER BY datname
`

func (q *Queries) ListDatabaseTemplates(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDatabaseTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var datname string
		if err := rows.Scan(&datname); err != nil {
			return nil, err
		}
		items = append(items, datname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabases = `-- name: ListDatabases :many

SELECT datname FROM pg_database
WHERE datallowconn AND NOT datistemplate
ORDER BY datname
`

// Server-level queries (run against maintenance DB)
func (q *Queries) ListDatabases(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var datname string
		if err := rows.Scan(&datname); err != nil {
			return nil, err
		}
		items = append(items, datname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainConstraints = `-- name: ListDomainConstraints :many
SELECT c.conname, pg_get_constraintdef(c.oid, true) AS definition
FROM pg_constraint c
WHERE c.contypid::int4 = $1
ORDER BY c.conname
`

type ListDomainConstraintsRow struct {
	Conname    string
	Definition string
}

func (q *Queries) ListDomainConstraints(ctx context.Context, contypid int32) ([]ListDomainConstraintsRow, error) {
	rows, err := q.db.Query(ctx, listDomainConstraints, contypid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDomainConstraintsRow
	for rows.Next() {
		var i ListDomainConstraintsRow
		if err := rows.Scan(&i.Conname, &i.Definition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT t.typname FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typtype = 'd'
ORDER BY 1
`

func (q *Queries) ListDomains(ctx context.Context, nspname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDomains, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var typname string
		if err := rows.Scan(&typname); err != nil {
			return nil, err
		}
		items = append(items, typname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncodings = `-- name: ListEncodings :many
SELECT name FROM pg_character_set
ORDER BY name
`

func (q *Queries) ListEncodings(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEncodings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnumLabels = `-- name: ListEnumLabels :many
SELECT e.enumlabel FROM pg_enum e
WHERE e.enumtypid::int4 = $1
ORDER BY e.enumsortorder
`

func (q *Queries) ListEnumLabels(ctx context.Context, enumtypid int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnumLabels, enumtypid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var enumlabel string
		if err := rows.Scan(&enumlabel); err != nil {
			return nil, err
		}
		items = append(items, enumlabel)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTriggers = `-- name: ListEventTriggers :many
SELECT evtname FROM pg_event_trigger ORDER BY 1
`

func (q *Queries) ListEventTriggers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var evtname string
		if err := rows.Scan(&evtname); err != nil {
			return nil, err
		}
		items = append(items, evtname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT extname FROM pg_extension ORDER BY 1
`

func (q *Queries) ListExtensions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var extname string
		if err := rows.Scan(&extname); err != nil {
			return nil, err
		}
		items = append(items, extname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignDataWrappers = `-- name: ListForeignDataWrappers :many
SELECT fdwname FROM pg_foreign_data_wrapper ORDER BY 1
`

func (q *Queries) ListForeignDataWrappers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listForeignDataWrappers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fdwname string
		if err := rows.Scan(&fdwname); err != nil {
			return nil, err
		}
		items = append(items, fdwname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunctions = `-- name: ListFunctions :many
SELECT p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')'
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = $1 AND p.prokind = 'f'
ORDER BY 1
`

func (q *Queries) ListFunctions(ctx context.Context, nspname string) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listFunctions, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT lanname FROM pg_language WHERE lanispl ORDER BY 1
`

func (q *Queries) ListLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var lanname string
		if err := rows.Scan(&lanname); err != nil {
			return nil, err
		}
		items = append(items, lanname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterializedViews = `-- name: ListMaterializedViews :many
SELECT matviewname FROM pg_matviews WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListMaterializedViews(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMaterializedViews, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var matviewname string
		if err := rows.Scan(&matviewname); err != nil {
			return nil, err
		}
		items = append(items, matviewname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT policyname FROM pg_policies
WHERE schemaname = $1 AND tablename = $2
ORDER BY 1
`

type ListPoliciesParams struct {
	Schemaname string
	Tablename  string
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Schemaname, arg.Tablename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var policyname string
		if err := rows.Scan(&policyname); err != nil {
			return nil, err
		}
		items = append(items, policyname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcedures = `-- name: ListProcedures :many
SELECT p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')'
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = $1 AND p.prokind = 'p'
ORDER BY 1
`

func (q *Queries) ListProcedures(ctx context.Context, nspname string) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listProcedures, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublications = `-- name: ListPublications :many
SELECT pubname FROM pg_publication ORDER BY 1
`

func (q *Queries) ListPublications(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPublications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pubname string
		if err := rows.Scan(&pubname); err != nil {
			return nil, err
		}
		items = append(items, pubname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT rolname FROM pg_roles
ORDER BY rolname
`

func (q *Queries) ListRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rolname string
		if err := rows.Scan(&rolname); err != nil {
			return nil, err
		}
		items = append(items, rolname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemas = `-- name: ListSchemas :many
SELECT nspname FROM pg_namespace
WHERE nspname NOT LIKE 'pg\_%' AND nspname <> 'information_schema'
ORDER BY 1
`

func (q *Queries) ListSchemas(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nspname string
		if err := rows.Scan(&nspname); err != nil {
			return nil, err
		}
		items = append(items, nspname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSequences = `-- name: ListSequences :many
SELECT sequencename FROM pg_sequences WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListSequences(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSequences, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sequencename string
		if err := rows.Scan(&sequencename); err != nil {
			return nil, err
		}
		items = append(items, sequencename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT subname FROM pg_subscription
WHERE subdbid = (SELECT oid FROM pg_database WHERE datname = current_database())
ORDER BY 1
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subname string
		if err := rows.Scan(&subname); err != nil {
			return nil, err
		}
		items = append(items, subname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableColumns = `-- name: ListTableColumns :many
SELECT column_name || ' ' || data_type FROM information_schema.columns
WHERE table_schema = $1 AND table_name = $2
ORDER BY ordinal_position
`

type ListTableColumnsParams struct {
	TableSchema interface{}
	TableName   interface{}
}

func (q *Queries) ListTableColumns(ctx context.Context, arg ListTableColumnsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listTableColumns, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableIndexes = `-- name: ListTableIndexes :many
SELECT cls.relname FROM pg_index idx
JOIN pg_class cls ON cls.oid = idx.indexrelid
JOIN pg_class tbl ON tbl.oid = idx.indrelid
JOIN pg_namespace ns ON tbl.relnamespace = ns.oid
WHERE ns.nspname = $1 AND tbl.relname = $2
ORDER BY 1
`

type ListTableIndexesParams struct {
	Nspname string
	Relname string
}

func (q *Queries) ListTableIndexes(ctx context.Context, arg ListTableIndexesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableIndexes, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var relname string
		if err := rows.Scan(&relname); err != nil {
			return nil, err
		}
		items = append(items, relname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableRules = `-- name: ListTableRules :many
SELECT rulename FROM pg_rules
WHERE schemaname = $1 AND tablename = $2
ORDER BY 1
`

type ListTableRulesParams struct {
	Schemaname string
	Tablename  string
}

func (q *Queries) ListTableRules(ctx context.Context, arg ListTableRulesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableRules, arg.Schemaname, arg.Tablename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rulename string
		if err := rows.Scan(&rulename); err != nil {
			return nil, err
		}
		items = append(items, rulename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableTriggers = `-- name: ListTableTriggers :many
SELECT tg.tgname FROM pg_trigger tg
JOIN pg_class t ON tg.tgrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2 AND NOT tg.tgisinternal
ORDER BY 1
`

type ListTableTriggersParams struct {
	Nspname string
	Relname string
}

func (q *Queries) ListTableTriggers(ctx context.Context, arg ListTableTriggersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableTriggers, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tgname string
		if err := rows.Scan(&tgname); err != nil {
			return nil, err
		}
		items = append(items, tgname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many

SELECT tablename FROM pg_tables WHERE schemaname = $1 ORDER BY 1
`

// Schema-level category queries ($1 = schema name)
func (q *Queries) ListTables(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTables, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tablename string
		if err := rows.Scan(&tablename); err != nil {
			return nil, err
		}
		items = append(items, tablename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablespaces = `-- name: ListTablespaces :many
SELECT spcname FROM pg_tablespace
ORDER BY spcname
`

func (q *Queries) ListTablespaces(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTablespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var spcname string
		if err := rows.Scan(&spcname); err != nil {
			return nil, err
		}
		items = append(items, spcname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT t.typname FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typtype IN ('c', 'e', 'r')
ORDER BY 1
`

func (q *Queries) ListTypes(ctx context.Context, nspname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTypes, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var typname string
		if err := rows.Scan(&typname); err != nil {
			return nil, err
		}
		items = append(items, typname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViews = `-- name: ListViews :many
SELECT viewname FROM pg_views WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListViews(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listViews, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var viewname string
		if err := rows.Scan(&viewname); err != nil {
			return nil, err
		}
		items = append(items, viewname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
