// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type DisconnectedDatabase struct {
	ServerID int64  `json:"server_id"`
	DbName   string `json:"db_name"`
}

type Process struct {
	Pid         int64          `json:"pid"`
	UserID      int64          `json:"user_id"`
	Desc        string         `json:"desc"`
	Type        string         `json:"type"`
	Status      int64          `json:"status"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     sql.NullTime   `json:"end_time"`
	LogDir      sql.NullString `json:"log_dir"`
	UtilityPath sql.NullString `json:"utility_path"`
}

type QueryHistory struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	TabID        sql.NullString `json:"tab_id"`
	ConnectionID sql.NullString `json:"connection_id"`
	QueryText    string         `json:"query_text"`
	ExecutedAt   sql.NullTime   `json:"executed_at"`
	DurationMs   sql.NullInt64  `json:"duration_ms"`
	Status       sql.NullString `json:"status"`
	RowsAffected sql.NullInt64  `json:"rows_affected"`
}

type Server struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	ServergroupID  int64          `json:"servergroup_id"`
	Name           string         `json:"name"`
	Host           string         `json:"host"`
	Port           int64          `json:"port"`
	MaintenanceDb  string         `json:"maintenance_db"`
	Username       string         `json:"username"`
	Password       sql.NullString `json:"password"`
	Role           sql.NullString `json:"role"`
	SslMode        string         `json:"ssl_mode"`
	Comment        sql.NullString `json:"comment"`
	DiscoveryID    sql.NullString `json:"discovery_id"`
	Hostaddr       sql.NullString `json:"hostaddr"`
	DbRes          sql.NullString `json:"db_res"`
	Passfile       sql.NullString `json:"passfile"`
	Sslcert        sql.NullString `json:"sslcert"`
	Keyfile        sql.NullString `json:"keyfile"`
	Rootcert       sql.NullString `json:"rootcert"`
	Crlfile        sql.NullString `json:"crlfile"`
	Service        sql.NullString `json:"service"`
	Bgcolor        sql.NullString `json:"bgcolor"`
	Fgcolor        sql.NullString `json:"fgcolor"`
	ConnectTimeout sql.NullInt64  `json:"connect_timeout"`
	UseSshTunnel   sql.NullInt64  `json:"use_ssh_tunnel"`
	SshHost        sql.NullString `json:"ssh_host"`
	SshPort        sql.NullInt64  `json:"ssh_port"`
	SshUsername    sql.NullString `json:"ssh_username"`
	SshPassword    sql.NullString `json:"ssh_password"`
	SshKeyfile     sql.NullString `json:"ssh_keyfile"`
	Shared         sql.NullBool   `json:"shared"`
	Disconnected   bool           `json:"disconnected"`
}

type Servergroup struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type Setting struct {
	ID      int64          `json:"id"`
	UserID  int64          `json:"user_id"`
	Setting string         `json:"setting"`
	Value   sql.NullString `json:"value"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	Password     string       `json:"password"`
	Active       bool         `json:"active"`
	ConfirmedAt  sql.NullTime `json:"confirmed_at"`
	SessionToken string       `json:"session_token"`
}

type UserPreference struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	PreferenceID int64  `json:"preference_id"`
	Value        string `json:"value"`
}

type UserWorkspace struct {
	UserID         int64          `json:"user_id"`
	ActiveTabID    string         `json:"active_tab_id"`
	LayoutMetadata sql.NullString `json:"layout_metadata"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type WorkspaceTab struct {
	ID           string         `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Title        string         `json:"title"`
	ConnectionID sql.NullString `json:"connection_id"`
	QueryText    sql.NullString `json:"query_text"`
	FilePath     sql.NullString `json:"file_path"`
	TabOrder     int64          `json:"tab_order"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}
